# Generated by Django 4.0.5 on 2022-06-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprisems.department')),
            ],
        ),
    ]
