# Generated by Django 4.0.5 on 2022-06-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisems', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
